# Generated by Django 2.2.10 on 2020-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0002_auto_20200312_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
