# Generated by Django 2.2.10 on 2020-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0004_auto_20200312_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
