# Generated by Django 2.2.10 on 2020-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20200322_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='rating',
        ),
        migrations.AddField(
            model_name='collection_has_games',
            name='difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection_has_games',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='collection_has_games',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
