# Generated by Django 2.2.10 on 2020-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20200322_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_has_games',
            name='game_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
